baseURL = 'https://smokkaya.github.io/icy-notebook/'
languageCode = 'fr'
title = 'Icy Notebook'
theme = "shibui"
enableGitInfo = true
copyright = "© 2026 Icy Notebook"

[params]
  author = "smokkaya"


[menu]
  [[menu.main]]
    name = "À propos"
    url = "/à-propos/"
    weight = 1